name: 'CCK Bug Report'
description: "Something isn't working as expected in the CCK."
title: '[CCK Bug] '
labels: ['type: bug', 'status: triage', 'in: cck']
projects: ['Alpha-Blend-Interactive/2']

body:

  - type: markdown
    attributes:
      value: |
        # Checklist

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission checklist
      options:
        - label: 'I checked that no other Bug Report describing my problem exists.'
          required: true
        - label: 'I accept that this issue may be closed if any of the above are found to be untrue.'
          required: true

  - type: markdown
    attributes:
      value: |
        # System Information

  - type: input
    id: platform
    attributes:
      label: Platform
      description: What platform are you using?
      placeholder: 'E.g.: Steam PC, Meta Quest, Pico, ..'
    validations:
      required: true

  - type: input
    id: os
    attributes:
      label: Operating System
      description: What Operating System are you using? If possible, please include the release version.
      placeholder: 'E.g.: Windows 10, Windows 11, Windows 11 24H2, ..'
    validations:
      required: True

  - type: markdown
    attributes:
      value: |
        # ChilloutVR Information

  - type: input
    id: game-version
    attributes:
      label: 'Game Version'
      description: What game version are you using? (You can find this in the main menu of the game)
      placeholder: 'E.g.: 2025r178, ..'
    validations:
      required: true

  - type: input
    id: cck-version
    attributes:
      label: 'CCK Version'
      description: What CCK version are you using?
      placeholder: 'E.g.: 3.12, ..'
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        # What happened?

  - type: textarea
    id: what-happened
    attributes:
      label: 'Describe what happened as precisely as possible.'
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        # What did you expect to happen?

  - type: textarea
    id: what-did-you-expect
    attributes:
      label: 'Describe what you expected to happen instead.'
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        # Steps to reproduce

  - type: textarea
    id: how-to-reproduce
    attributes:
      label: 'In as much detail as possible, describe the exact steps you took to make the problem appear.'
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        # Anything else?

  - type: textarea
    id: anything-else
    attributes:
      label: 'Other remarks'
    validations:
      required: false
